services:
  db:
    image: postgres:18
    container_name: posts_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - posts_network
    env_file:
      - .env

  migrate:
    image: kukymbr/goose-docker:3.26.0
    container_name: posts_migrate
    environment:
      GOOSE_DRIVER: ${DB_PROTOCOL}
      GOOSE_DBSTRING: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} ${DB_OPTIONS}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - posts_network
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: posts_app
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_OPTIONS: ${DB_OPTIONS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - posts_network
    env_file:
      - .env

volumes:
  db_data:
networks:
  posts_network:
    driver: bridge